events {
    worker_connections 1024;
}

http {
    # 1. 분산시킬 서버 그룹을 정의합니다. (Round-Robin 방식)
    upstream spring_servers {
        server dc-server-1:8080;
        server dc-server-2:8080;
        server dc-server-3:8080;
    }

    server {
        # 2. 클라이언트가 80번 포트로 들어오면
        listen 80;

        location / {
            # 3. 위에서 정의한 spring_servers 그룹으로 트래픽을 던집니다.
            proxy_pass http://spring_servers;

            # 헤더 정보 유지
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}